#!/bin/bash

BASE_DIR=$(dirname -- $(realpath -- $0))

RODE0DAYPRD_REPO_DIR=$BASE_DIR
RODE0DAY_version="19.11"
RODE0DAY_REPO_DIR="$RODE0DAY_REPO_DIR/$RODE0DAY_version"
RODE0DAY_TAR="$RODE0DAY_version.tar.gz"


pushd $BASE_DIR
if [ ! -e "$BASE_DIR/$RODE0DAY_TAR" ]; then
wget https://rode0day.mit.edu/static/archive/$RODE0DAY_TAR
fi
if [ ! -d $RODE0DAY_REPO_DIR ]; then
tar xvzf $RODE0DAY_TAR
fi




popd